name: Auto Booking Performance Lab

on:
  schedule:
    - cron: "30 17 * * *"
  workflow_dispatch:

jobs:
  booking:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chromium:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size="2g"

    steps:

      - name: Debug Docker
        run: docker ps -a

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Selenium
        run: |
          echo "[SYSTEM] Checking Selenium readiness..."
          for i in {1..30}; do
            STATUS=$(curl -s http://localhost:4444/wd/hub/status || echo "")
            if echo "$STATUS" | grep -q '"ready":true'; then
              echo "[SYSTEM] Selenium is ready!"
              exit 0
            fi
            echo "[SYSTEM] Retry $i..."
            sleep 2
          done
          echo "[ERROR] Selenium did NOT start"
          exit 1

      - name: Run Auto Booking
        id: booking_step
        run: |
          echo "[BOT] Start booking" > booking_log.txt
          python main.py >> booking_log.txt 2>&1 || true
          echo "log_path=booking_log.txt" >> $GITHUB_OUTPUT

      - name: Show log
        if: always()
        run: |
          cat booking_log.txt

      - name: Send Discord Notification
        run: |
          python notify.py "${{ steps.booking_step.outputs.log_path }}"
